<?xml version="1.0" encoding="UTF-8"?>
<!--
   New Perspectives on XML
   Tutorial 5
   Case Problem 2

   Periodic Table of the Elements
   Author: Efrem McCrimon
   date:   02-22-2011

   Filename:         elements.xml
   Supporting Files: pchart.css
 
-->

<!DOCTYPE all_elements
[
   <!ELEMENT all_elements (heading, heading2, heading3, ch_element+) >

   <!ELEMENT heading (#PCDATA)>
   <!ELEMENT heading2 (#PCDATA)>
   <!ELEMENT heading3 (#PCDATA)>

   <!ELEMENT ch_element (number, symbol, wgt)>
   <!ATTLIST ch_element id ID #REQUIRED>

   <!ELEMENT number (#PCDATA)>
   <!ELEMENT symbol (#PCDATA)>
   <!ELEMENT wgt (#PCDATA)>
]>

<?xml-stylesheet type="text/css" href="pchart-safari.css" ?>
<all_elements>
   <heading>Periodic Chart of the Elements</heading>
   <heading2>* Lanthanide Series</heading2>
   <heading3>** Actinide Series</heading3>

   <ch_element id="e1">
      <number>1</number>
      <symbol>H</symbol>
      <wgt>1.00797</wgt>
   </ch_element>
   <ch_element id="e1a">
      <number>1</number>
      <symbol>H</symbol>
      <wgt>1.00797</wgt>
   </ch_element>
   <ch_element id="e2">
      <number>2</number>
      <symbol>He</symbol>
      <wgt>4.0026</wgt>
   </ch_element>
   <ch_element id="e3">
      <number>3</number>
      <symbol>Li</symbol>
      <wgt>6.939</wgt>
   </ch_element>
   <ch_element id="e4">
      <number>4</number>
      <symbol>Be</symbol>
      <wgt>9.0122</wgt>
   </ch_element>
   <ch_element id="e5">
      <number>5</number>
      <symbol>B</symbol>
      <wgt>10.811</wgt>
   </ch_element>
   <ch_element id="e6">
      <number>6</number>
      <symbol>C</symbol>
      <wgt>12.0112</wgt>
   </ch_element>
   <ch_element id="e7">
      <number>7</number>
      <symbol>N</symbol>
      <wgt>14.0067</wgt>
   </ch_element>
   <ch_element id="e8">
      <number>8</number>
      <symbol>O</symbol>
      <wgt>15.994</wgt>
   </ch_element>
   <ch_element id="e9">
      <number>9</number>
      <symbol>F</symbol>
      <wgt>18.9984</wgt>
   </ch_element>
   <ch_element id="e10">
      <number>10</number>
      <symbol>Ne</symbol>
      <wgt>20.183</wgt>
   </ch_element>
   <ch_element id="e11">
      <number>11</number>
      <symbol>Na</symbol>
      <wgt>22.9898</wgt>
   </ch_element>
   <ch_element id="e12">
      <number>12</number>
      <symbol>Mg</symbol>
      <wgt>24.312</wgt>
   </ch_element>
   <ch_element id="e13">
      <number>13</number>
      <symbol>Al</symbol>
      <wgt>26.9815</wgt>
   </ch_element>
   <ch_element id="e14">
      <number>14</number>
      <symbol>Si</symbol>
      <wgt>28.086</wgt>
   </ch_element>
   <ch_element id="e15">
      <number>15</number>
      <symbol>P</symbol>
      <wgt>30.9738</wgt>
   </ch_element>
   <ch_element id="e16">
      <number>16</number>
      <symbol>S</symbol>
      <wgt>32.064</wgt>
   </ch_element>
   <ch_element id="e17">
      <number>17</number>
      <symbol>Cl</symbol>
      <wgt>35.453</wgt>
   </ch_element>
   <ch_element id="e18">
      <number>18</number>
      <symbol>Ar</symbol>
      <wgt>39.948</wgt>
   </ch_element>
   <ch_element id="e19">
      <number>19</number>
      <symbol>K</symbol>
      <wgt>39.102</wgt>
   </ch_element>
   <ch_element id="e20">
      <number>20</number>
      <symbol>Ca</symbol>
      <wgt>40.08</wgt>
   </ch_element>
   <ch_element id="e21">
      <number>21</number>
      <symbol>Sc</symbol>
      <wgt>44.956</wgt>
   </ch_element>
   <ch_element id="e22">
      <number>22</number>
      <symbol>Ti</symbol>
      <wgt>47.90</wgt>
   </ch_element>
   <ch_element id="e23">
      <number>23</number>
      <symbol>V</symbol>
      <wgt>50.942</wgt>
   </ch_element>
   <ch_element id="e24">
      <number>24</number>
      <symbol>Cr</symbol>
      <wgt>51.996</wgt>
   </ch_element>
   <ch_element id="e25">
      <number>25</number>
      <symbol>Mn</symbol>
      <wgt>54.938</wgt>
   </ch_element>
   <ch_element id="e26">
      <number>26</number>
      <symbol>Fe</symbol>
      <wgt>55.847</wgt>
   </ch_element>
   <ch_element id="e27">
      <number>27</number>
      <symbol>Co</symbol>
      <wgt>58.9332</wgt>
   </ch_element>
   <ch_element id="e28">
      <number>28</number>
      <symbol>Ni</symbol>
      <wgt>58.71</wgt>
   </ch_element>
   <ch_element id="e29">
      <number>29</number>
      <symbol>Cu</symbol>
      <wgt>63.54</wgt>
   </ch_element>
   <ch_element id="e30">
      <number>30</number>
      <symbol>Zn</symbol>
      <wgt>65.37</wgt>
   </ch_element>
   <ch_element id="e31">
      <number>31</number>
      <symbol>Ga</symbol>
      <wgt>69.72</wgt>
   </ch_element>
   <ch_element id="e32">
      <number>32</number>
      <symbol>Ge</symbol>
      <wgt>72.59</wgt>
   </ch_element>
   <ch_element id="e33">
      <number>33</number>
      <symbol>As</symbol>
      <wgt>74.9216</wgt>
   </ch_element>
   <ch_element id="e34">
      <number>34</number>
      <symbol>Se</symbol>
      <wgt>78.96</wgt>
   </ch_element>
   <ch_element id="e35">
      <number>35</number>
      <symbol>Br</symbol>
      <wgt>79.909</wgt>
   </ch_element>
   <ch_element id="e36">
      <number>36</number>
      <symbol>Kr</symbol>
      <wgt>83.80</wgt>
   </ch_element>
   <ch_element id="e37">
      <number>37</number>
      <symbol>Rb</symbol>
      <wgt>85.47</wgt>
   </ch_element>
   <ch_element id="e38">
      <number>38</number>
      <symbol>Sr</symbol>
      <wgt>87.62</wgt>
   </ch_element>
   <ch_element id="e39">
      <number>39</number>
      <symbol>Y</symbol>
      <wgt>88.905</wgt>
   </ch_element>
   <ch_element id="e40">
      <number>40</number>
      <symbol>Zr</symbol>
      <wgt>91.22</wgt>
   </ch_element>
   <ch_element id="e41">
      <number>41</number>
      <symbol>Nb</symbol>
      <wgt>92.906</wgt>
   </ch_element>
   <ch_element id="e42">
      <number>42</number>
      <symbol>Mo</symbol>
      <wgt>95.94</wgt>
   </ch_element>
   <ch_element id="e43">
      <number>43</number>
      <symbol>Tc</symbol>
      <wgt>99</wgt>
   </ch_element>
   <ch_element id="e44">
      <number>44</number>
      <symbol>Ru</symbol>
      <wgt>101.07</wgt>
   </ch_element>
   <ch_element id="e45">
      <number>45</number>
      <symbol>Rh</symbol>
      <wgt>102.905</wgt>
   </ch_element>
   <ch_element id="e46">
      <number>46</number>
      <symbol>Pd</symbol>
      <wgt>106.4</wgt>
   </ch_element>
   <ch_element id="e47">
      <number>47</number>
      <symbol>Ag</symbol>
      <wgt>107.870</wgt>
   </ch_element>
   <ch_element id="e48">
      <number>48</number>
      <symbol>Cd</symbol>
      <wgt>112.40</wgt>
   </ch_element>
   <ch_element id="e49">
      <number>49</number>
      <symbol>In</symbol>
      <wgt>114.82</wgt>
   </ch_element>
   <ch_element id="e50">
      <number>50</number>
      <symbol>Sn</symbol>
      <wgt>118.69</wgt>
   </ch_element>
   <ch_element id="e51">
      <number>51</number>
      <symbol>Sb</symbol>
      <wgt>121.75</wgt>
   </ch_element>
   <ch_element id="e52">
      <number>52</number>
      <symbol>Te</symbol>
      <wgt>127.60</wgt>
   </ch_element>
   <ch_element id="e53">
      <number>53</number>
      <symbol>I</symbol>
      <wgt>126.904</wgt>
   </ch_element>
   <ch_element id="e54">
      <number>54</number>
      <symbol>Xe</symbol>
      <wgt>131.30</wgt>
   </ch_element>
   <ch_element id="e55">
      <number>55</number>
      <symbol>Cs</symbol>
      <wgt>132.905</wgt>
   </ch_element>
   <ch_element id="e56">
      <number>56</number>
      <symbol>Ba</symbol>
      <wgt>137.34</wgt>
   </ch_element>
   <ch_element id="e57">
      <number>57*</number>
      <symbol>La</symbol>
      <wgt>138.91</wgt>
   </ch_element>
   <ch_element id="e58">
      <number>58</number>
      <symbol>Ce</symbol>
      <wgt>140.12</wgt>
   </ch_element>
   <ch_element id="e59">
      <number>59</number>
      <symbol>Pr</symbol>
      <wgt>140.907</wgt>
   </ch_element>
   <ch_element id="e60">
      <number>60</number>
      <symbol>Nd</symbol>
      <wgt>144.24</wgt>
   </ch_element>
   <ch_element id="e61">
      <number>61</number>
      <symbol>Pm</symbol>
      <wgt>147</wgt>
   </ch_element>
   <ch_element id="e62">
      <number>62</number>
      <symbol>Sm</symbol>
      <wgt>150.35</wgt>
   </ch_element>
   <ch_element id="e63">
      <number>63</number>
      <symbol>Eu</symbol>
      <wgt>151.96</wgt>
   </ch_element>
   <ch_element id="e64">
      <number>64</number>
      <symbol>Gd</symbol>
      <wgt>157.25</wgt>
   </ch_element>
   <ch_element id="e65">
      <number>65</number>
      <symbol>Tb</symbol>
      <wgt>158.924</wgt>
   </ch_element>
   <ch_element id="e66">
      <number>66</number>
      <symbol>Dy</symbol>
      <wgt>162.50</wgt>
   </ch_element>
   <ch_element id="e67">
      <number>67</number>
      <symbol>Ho</symbol>
      <wgt>164.930</wgt>
   </ch_element>
   <ch_element id="e68">
      <number>68</number>
      <symbol>Er</symbol>
      <wgt>167.26</wgt>
   </ch_element>
   <ch_element id="e69">
      <number>69</number>
      <symbol>Tm</symbol>
      <wgt>168.934</wgt>
   </ch_element>
   <ch_element id="e70">
      <number>70</number>
      <symbol>Yb</symbol>
      <wgt>173.04</wgt>
   </ch_element>
   <ch_element id="e71">
      <number>71</number>
      <symbol>Lu</symbol>
      <wgt>174.97</wgt>
   </ch_element>
   <ch_element id="e72">
      <number>72</number>
      <symbol>Hf</symbol>
      <wgt>178.49</wgt>
   </ch_element>
   <ch_element id="e73">
      <number>73</number>
      <symbol>Ta</symbol>
      <wgt>180.948</wgt>
   </ch_element>
   <ch_element id="e74">
      <number>74</number>
      <symbol>W</symbol>
      <wgt>183.85</wgt>
   </ch_element>
   <ch_element id="e75">
      <number>75</number>
      <symbol>Re</symbol>
      <wgt>186.2</wgt>
   </ch_element>
   <ch_element id="e76">
      <number>76</number>
      <symbol>Os</symbol>
      <wgt>190.2</wgt>
   </ch_element>
   <ch_element id="e77">
      <number>77</number>
      <symbol>Ir</symbol>
      <wgt>192.2</wgt>
   </ch_element>
   <ch_element id="e78">
      <number>78</number>
      <symbol>Pt</symbol>
      <wgt>195.09</wgt>
   </ch_element>
   <ch_element id="e79">
      <number>79</number>
      <symbol>Au</symbol>
      <wgt>196.967</wgt>
   </ch_element>
   <ch_element id="e80">
      <number>80</number>
      <symbol>Hg</symbol>
      <wgt>200.59</wgt>
   </ch_element>
   <ch_element id="e81">
      <number>81</number>
      <symbol>Tl</symbol>
      <wgt>204.37</wgt>
   </ch_element>
   <ch_element id="e82">
      <number>82</number>
      <symbol>Pb</symbol>
      <wgt>207.19</wgt>
   </ch_element>
   <ch_element id="e83">
      <number>83</number>
      <symbol>Bi</symbol>
      <wgt>208.980</wgt>
   </ch_element>
   <ch_element id="e84">
      <number>84</number>
      <symbol>Po</symbol>
      <wgt>210</wgt>
   </ch_element>
   <ch_element id="e85">
      <number>85</number>
      <symbol>At</symbol>
      <wgt>210</wgt>
   </ch_element>
   <ch_element id="e86">
      <number>86</number>
      <symbol>Rn</symbol>
      <wgt>222</wgt>
   </ch_element>
   <ch_element id="e87">
      <number>87</number>
      <symbol>Fr</symbol>
      <wgt>223</wgt>
   </ch_element>
   <ch_element id="e88">
      <number>88</number>
      <symbol>Ra</symbol>
      <wgt>226</wgt>
   </ch_element>
   <ch_element id="e89">
      <number>89**</number>
      <symbol>Ac</symbol>
      <wgt>227</wgt>
   </ch_element>
   <ch_element id="e90">
      <number>90</number>
      <symbol>Th</symbol>
      <wgt>232.038</wgt>
   </ch_element>
   <ch_element id="e91">
      <number>91</number>
      <symbol>Pa</symbol>
      <wgt>231</wgt>
   </ch_element>
   <ch_element id="e92">
      <number>92</number>
      <symbol>U</symbol>
      <wgt>238.03</wgt>
   </ch_element>
   <ch_element id="e93">
      <number>93</number>
      <symbol>Np</symbol>
      <wgt>237</wgt>
   </ch_element>
   <ch_element id="e94">
      <number>94</number>
      <symbol>Pu</symbol>
      <wgt>242</wgt>
   </ch_element>
   <ch_element id="e95">
      <number>95</number>
      <symbol>Am</symbol>
      <wgt>243</wgt>
   </ch_element>
   <ch_element id="e96">
      <number>96</number>
      <symbol>Cm</symbol>
      <wgt>247</wgt>
   </ch_element>
   <ch_element id="e97">
      <number>97</number>
      <symbol>Bk</symbol>
      <wgt>247</wgt>
   </ch_element>
   <ch_element id="e98">
      <number>98</number>
      <symbol>Cf</symbol>
      <wgt>249</wgt>
   </ch_element>
   <ch_element id="e99">
      <number>99</number>
      <symbol>Es</symbol>
      <wgt>254</wgt>
   </ch_element>
   <ch_element id="e100">
      <number>100</number>
      <symbol>Fm</symbol>
      <wgt>253</wgt>
   </ch_element>
   <ch_element id="e101">
      <number>101</number>
      <symbol>Md</symbol>
      <wgt>256</wgt>
   </ch_element>
   <ch_element id="e102">
      <number>102</number>
      <symbol>No</symbol>
      <wgt>256</wgt>
   </ch_element>
   <ch_element id="e103">
      <number>103</number>
      <symbol>Lr</symbol>
      <wgt>257</wgt>
   </ch_element>
   <ch_element id="e104">
      <number>104</number>
      <symbol>Rf</symbol>
      <wgt>261</wgt>
   </ch_element>
   <ch_element id="e105">
      <number>105</number>
      <symbol>Db</symbol>
      <wgt>262</wgt>
   </ch_element>
   <ch_element id="e106">
      <number>106</number>
      <symbol>Sg</symbol>
      <wgt>266</wgt>
   </ch_element>
   <ch_element id="e107">
      <number>107</number>
      <symbol>Bh</symbol>
      <wgt>262</wgt>
   </ch_element>
   <ch_element id="e108">
      <number>108</number>
      <symbol>Hs</symbol>
      <wgt>265</wgt>
   </ch_element>
   <ch_element id="e109">
      <number>109</number>
      <symbol>Mt</symbol>
      <wgt>266</wgt>
   </ch_element>
   <ch_element id="e110">
      <number>110</number>
      <symbol>?</symbol>
      <wgt>271</wgt>
   </ch_element>
   <ch_element id="e111">
      <number>111</number>
      <symbol>?</symbol>
      <wgt>272</wgt>
   </ch_element>
   <ch_element id="e112">
      <number>112</number>
      <symbol>?</symbol>
      <wgt>277</wgt>
   </ch_element>

</all_elements>